package az.ingress.model.constant;

public interface ExceptionConstant {
    String AUTHOR_NOT_FOUND = "AUTHOR_NOT_FOUND";
    String BOOK_NOT_FOUND = "BOOK_NOT_FOUND";
    String STUDENT_NOT_FOUND = "STUDENT_NOT_FOUND";
    String USER_NOT_FOUND = "USER_NOT_FOUND";
    String USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS";
    String UNEXPECTED_EXCEPTION = "UNEXPECTED_EXCEPTION";
    String VALIDATION_EXCEPTION = "VALIDATION_EXCEPTION";
    String TOKEN_EXPIRED = "TOKEN_EXPIRED";
    String USER_UNAUTHORIZED = "USER_UNAUTHORIZED";
    String REFRESH_TOKEN_EXPIRED = "REFRESH_TOKEN_EXPIRED";
    String REFRESH_TOKEN_COUNT_EXPIRED = "REFRESH_TOKEN_COUNT_EXPIRED";
}